### ISSUE TITLE
NanException when using the Run and Upscale page

### ISSUE THREAD

**Issue by pto2k** [AIrjen/OneButtonPrompt#87] opened 2023-07-12 17:39 UTC
Hi,
I had this issus while using the Run and Upscale tab.
Generated 1st image fine, and then hit this on the second attempt.

My settings and console output in screenshots: https://imgur.com/a/24tyw81

Please have a look.

Thank you.

`│ E:\Repo\stable-diffusion-webui\modules\devices.py:158 in test_for_nans                                                                                               │
│                                                                                                                                                                      │
│   157 │                                                                                                                                                              │
│ ❱ 158 │   raise NansException(message)                                                                                                                               │
│   159                                                                                                                                                                │
│                                                                                                                                                                      │
│ ╭───────────────────────────────────────────── locals ─────────────────────────────────────────────╮                                                                 │
│ │ message = "A tensor with all NaNs was produced in Unet. This could be either because there'"+324 │                                                                 │
│ │  shared = <module 'modules.shared' from 'E:\\Repo\\stable-diffusion-webui\\modules\\shared.py'>  │                                                                 │
│ │   where = 'unet'                                                                                 │                                                                 │
│ │       x = tensor([[[[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]],                                       │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │    [[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]],                                       │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │    [[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]],                                       │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │    [[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]]],                                      │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │   [[[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]],                                       │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │    [[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]],                                       │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │    [[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]],                                       │                                                                 │
│ │           │   │                                                                                  │                                                                 │
│ │           │   │    [[nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     ...,                                                                         │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan],                                        │                                                                 │
│ │           │   │     [nan, nan, nan,  ..., nan, nan, nan]]]], device='cuda:0')                    │                                                                 │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
NansException: A tensor with all NaNs was produced in Unet. This could be either because there's not enough precision to represent the picture, or because your video
card does not support half type. Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline
argument to fix this. Use --disable-nan-check commandline argument to disable this check.
If this keeps happening: Is WebUI started with --api enabled?

Traceback (most recent call last):
  File "E:\Repo\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Repo\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "E:\Repo\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Repo\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Repo\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "E:\Repo\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "E:\Repo\stable-diffusion-webui\extensions\OneButtonPrompt\main.py", line 140, in generateimages
    txt2img = call_txt2img(randomprompt, size ,hiresfix, 0, filenamecomplete,model ,samplingsteps,cfg, hiressteps, denoisestrength,samplingmethod, upscaler,hiresscale,apiurl,qualitygate,quality,runs,negativeprompt)
  File "E:\Repo\stable-diffusion-webui\extensions\OneButtonPrompt\call_txt2img.py", line 149, in call_txt2img
    raise ValueError("API has not been responding after several retries. Stopped processing.")
ValueError: API has not been responding after several retries. Stopped processing.
`

**Comment by AIrjen** [comment] 2023-07-13 05:46
Hi, this looks like a webui/model problem. Have you tried the suggestions it gives?

Try setting the "Upcast cross attention layer to float32" option in Settings > Stable Diffusion or using the --no-half commandline
argument to fix this. Use --disable-nan-check commandline argument to disable this check.

One other thing to check is your videocard driver, I heard some people having issues with latest video card driver from Nvidia.


You can do some checks wether it works with base SD1.5 to see if its a problem with the model (or a LoRA).

**Comment by AIrjen** [comment] 2023-07-13 06:12
Ps, I am currently not at home so I can’t run a full reproduction scenario. I love the attached settings, Art Blaster and “the X of Y concepts” are both personal favorites.

**Comment by pto2k** [comment] 2023-07-13 18:13
Hi, 
I tried adding the commandline options and also using other checkpoints and generation types. But still have the error.
I guess it is some other extensions or scripts I'm using causing the issue. Need to test some more.
Thanks.

**Comment by AIrjen** [comment] 2023-07-16 12:27
Update: I am back home, and I am able to consistenlty eproduce the issue. (The settings you screenshotted really helped!)

At first I was working with several different Nvidia drivers, but that does not seem to be the issue.

I am currently looking through the code. I think I have spotted something that could cause an issue. I am working on this!

**Comment by AIrjen** [comment] 2023-07-16 19:19
Workaround: Choose a different model to use for both the txt2img and img2img processes.

So this took me some time to figure out. Basically what happens, is that there is a memory leak somewhere in WebUI. This is resolved by loading and unloading the models.

So, what I need to build, is a trick to load/unload models in the background while processing. I know what code to use to load a model, I just need to see how I can locate the currently loaded model properly. Will work on this, hopefully I can finalize this in the coming week or weekend. The workaround should work (for example load up dreamshaper v7 and v6).

**Comment by pto2k** [comment] 2023-07-17 12:29
Thanks for the update and workaround tip!

**Comment by AIrjen** [comment] 2023-08-11 17:19
I have pushed one last change for this one.

It no longer defaults to swapping models. Instead it nicely unloads and reloads the active model. This should help a bit in total. Overall, that is the extend of what I can do.

**Closed by AIrjen** 2023-08-11 17:19 UTC
