### ISSUE TITLE
Cannot select all upscaler in One Button Run and Upscale

### ISSUE THREAD

**Issue by DoctorBlackZ33** [AIrjen/OneButtonPrompt#49] opened 2023-06-19 20:53 UTC
for some reason the dropdown menu shows only all or automatic except in higresfix there it shows the latent ones. im using vladmanic webui. When i use all it randomly selects one and sometimes even downloads the ones i dont have, why is that? i cannot ifnd the problem in the python scripts so i might have overlooked it

**Comment by AIrjen** [comment] 2023-06-20 06:14
Hi, I've been able to reproduce the problem.

When I do I fresh start of Vladmantic, the models don't show up. If I then go to "extensions" and then "Apply changes and restart server" they do show up. (or go to "settings" and press "restart server").

I think it's an issue with caching/loading somewhere in Vladmantic. A hunch is that "OneButtonPrompt" is loaded before the rest of Vladmantic on startup, and the upscalers are not yet known to it. The latent ones are hardcoded, and will always show up. In the startup screen you can see it "preloading" the extensions, and then after it it will load the libraries.

Looks like this is the workaround for now.

As for the downloading, that is something that Vlad build. WebUI only shows what you have downloaded, Vlad shows what you could be using, and downloads it when you haven't used it yet. So it is part of Vladmantic.

**Comment by DoctorBlackZ33** [comment] 2023-06-20 06:27
> Hi, I've been able to reproduce the problem.
> 
> When I do I fresh start of Vladmantic, the models don't show up. If I then go to "extensions" and then "Apply changes and restart server" they do show up. (or go to "settings" and press "restart server").
> 
> I think it's an issue with caching/loading somewhere in Vladmantic. A hunch is that "OneButtonPrompt" is loaded before the rest of Vladmantic on startup, and the upscalers are not yet known to it. The latent ones are hardcoded, and will always show up. In the startup screen you can see it "preloading" the extensions, and then after it it will load the libraries.
> 
> Looks like this is the workaround for now.
> 
> As for the downloading, that is something that Vlad build. WebUI only shows what you have downloaded, Vlad shows what you could be using, and downloads it when you haven't used it yet. So it is part of Vladmantic.

thanks mate i see the problem, im not good enough with the python code of the web ui to fix it myself but thanks regardless. if i want to generate and upscale i will just restart it in the extensions tab. let me know if another fix comes available and thanks again for your work its an amazing script.

**Comment by AIrjen** [comment] 2023-06-30 09:56
I've just pushed a first fix out. For WebUI 1.4, it is still not perfect but better.

Same fix does seem to solve the this issue in Vlad completely.

**Comment by AIrjen** [comment] 2023-07-01 13:21
Got another fix in. I now just keep reloading the upscalers each time the code hits this part. That seems to work.
Tested on both WebUI 1.4 and Vlad.

Closing this for now. Might need to do some manual updates if new upscalers are added into either.

**Closed by AIrjen** 2023-07-01 13:21 UTC
