### ISSUE TITLE
Bug: textual version not processed

### ISSUE THREAD

**Issue by devilkkw** [AIrjen/OneButtonPrompt#28] opened 2023-05-15 17:20 UTC
If you add textual inversion in "add after" or "add before" textbox, is used like a normal text and not used as textual inversion.
Also it is ignored  in the chosen style.

**Comment by AIrjen** [comment] 2023-05-15 18:51
Hi, I have been using this. I just tried again on the latest version, and textual inversions are working for me. So I cannot reproduce this.

The prompt generator does nothing different than adding all the fields together, and pass them to the WebUI as it would in a normal prompt.

What happens if you copy the same prompt and use it as normal?

It could be that some of the other fields are too strong and overpowering the result?

Does your textual inversion also need a trigger word?

You can also try and form it like this __(style-silvamagic:2)__ to really give the textual inversion a punch up.

**Comment by AIrjen** [comment] 2023-05-16 06:39
Sorry I can't help with this right now.

I'll keep this issue open for now.
- Other users that have the same problem can report here
- If you do find anything, report back here. Then I can look into it, or we can document the issue.

**Comment by AIrjen** [comment] 2023-06-19 16:51
Hi, I'm closing this. There have been no other reports or similar issues from other users.

**Closed by AIrjen** 2023-06-19 16:51 UTC
