### ISSUE TITLE
UnicodeDecodeError: utf-8

### ISSUE THREAD

**Issue by Rank66** [AIrjen/OneButtonPrompt#157] opened 2024-01-18 12:25 UTC
I had an error generating the image
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 15: invalid start byte"
I found out where the problem was coming from, it's the 'artists.csv' file which contains accents not compatible with Stable Diffusion and A1111.
I've corrected the problem by replacing the accented characters with the unaccented equivalent

**Comment by AIrjen** [comment] 2024-01-18 17:55
Thanks! That seems to be something new. I'll adjust the csv's in the next update. (probably this weekend somewhere)

**Comment by AIrjen** [comment] 2024-01-19 07:40
Hi Rank66, what OS are you running on and are you using latest version?

I am having trouble reproducing the error. For example, I have been testing with "Zdzisław Beksiński", the artist with the most accents ;) and everything is just working fine?

I check all the code that reads from the csv's, and they are all marked as reading with 'utf-8' encoding.

**Comment by AIrjen** [comment] 2024-03-02 07:45
Can't reproduce, not enough information to continue. Haven't seen anyone else with this issue as well. Closing this for now.

**Closed by AIrjen** 2024-03-02 07:45 UTC
