### ISSUE TITLE
Pretty consistent (but not all the time) error. 

### ISSUE THREAD

**Issue by MrGingerSir222** [AIrjen/OneButtonPrompt#39] opened 2023-06-03 00:08 UTC
I get this message a lot. I'm not extremely tec savvy, so it might be slightly different each time, but it always ends the same way. It does not always happen though. It seems rather random. I'm never able to produce a long list of images though, since it is more likely to happen than not if I'm running even 4 image generations at a time. Anything higher than that is doomed for me personally. 
Here is the command lines and error:

Setting insanity level to 5
adding something rare to the prompt
Nice! adding something legendary to the prompt
extreme wide shot of a Dunmer with a Elk, Geass, Face mask, from inside of a Impressive Hotel, at Dusk, Knightcore, 50mm
Going to run with sampling method Heun
Going to run with upscaler Latent (nearest-exact)
Traceback (most recent call last):
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\extensions\OneButtonPrompt\main.py", line 140, in generateimages
    txt2img = call_txt2img(randomprompt, size ,hiresfix, 0, filenamecomplete,model ,samplingsteps,cfg, hiressteps, denoisestrength,samplingmethod, upscaler,hiresscale,apiurl,qualitygate,quality,runs,negativeprompt)
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\extensions\OneButtonPrompt\call_txt2img.py", line 138, in call_txt2img
    for i in r['images']:
KeyError: 'images'

**Comment by AIrjen** [comment] 2023-06-03 05:39
I had to try the prompt first, looks like you missed out on a good one!

![00000-294695677](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/2f237a60-66b4-4b3e-ade0-453e104572ef)

For the error, I have had similar experiences. On my PC this would happen if the image before this one would fail with an Out of Memory error. The next one it picks up will give this error.

Can you check wether this is the case for you as well?

I can tell by the messages, that you are running with random samplers and upscalers. It might be worth setting these to values you know your PC can handle, to see if that improves the problem.

In the meantime, I will keep an eye out for these kind of messages.

Let me know if you find any Out of Memory messages as well.

**Comment by MrGingerSir222** [comment] 2023-06-03 11:52
Thanks for the reply!

I can have this happen on the very first image, the moment I hit the generate button as well (which is what happened with this particular example I believe). 
Another issue that might be contributing towards this one is that the extension seems unable to find my upscale models. I will include some images showing how a111 can see the models, but OneButtonPrompt cannot:

<img width="1470" alt="Screenshot 2023-06-03 at 6 49 22 AM" src="https://github.com/AIrjen/OneButtonPrompt/assets/112094794/e43a78cb-a078-4691-91b3-fa3a81a00505">

<img width="1470" alt="Screenshot 2023-06-03 at 6 49 03 AM" src="https://github.com/AIrjen/OneButtonPrompt/assets/112094794/6353ec10-e17b-4f8a-83a0-6d9e7363bc9c">

<img width="1470" alt="Screenshot 2023-06-03 at 6 48 49 AM" src="https://github.com/AIrjen/OneButtonPrompt/assets/112094794/d3441f2f-4a81-4070-86cb-af35fb2d7951">

**Comment by MrGingerSir222** [comment] 2023-06-03 12:01
Thank you for the reply!

This issue can occur on the very first image, the moment I press the generation button as well. 
Another issue that might be connected is that the extension is unable to find my upscalers for some reason. 
I will attach some images that show how my SD is able to find my upscale models, but OneButtonPrompt is not:

<img width="687" alt="Screenshot 2023-06-03 at 6 49 22 AM" src="https://github.com/AIrjen/OneButtonPrompt/assets/112094794/43df9a4b-9757-4372-8983-51edb81cd776">

<img width="703" alt="Screenshot 2023-06-03 at 6 49 03 AM" src="https://github.com/AIrjen/OneButtonPrompt/assets/112094794/64a315e2-4727-4f9d-ae2d-f673231bd88c">

<img width="707" alt="Screenshot 2023-06-03 at 6 48 49 AM" src="https://github.com/AIrjen/OneButtonPrompt/assets/112094794/b6b78d97-3434-48b0-9a51-accd433ac465">

**Comment by MrGingerSir222** [comment] 2023-06-03 13:16
update: 
the upscale model issue was with Vlad SD Next, and I found a fix.

However, I still get similar errors even using settings I know my pc can handle.

Traceback (most recent call last):
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\extensions\OneButtonPrompt\main.py", line 194, in generateimages
    img2img = call_img2img(image, originalimage, originalpnginfo, apiurl, filenamecomplete, randomprompt,negativeprompt,img2imgsamplingsteps, img2imgcfg, img2imgsamplingmethod, img2imgupscaler, img2imgmodel, img2imgdenoisestrength, img2imgscale, img2imgpadding,upscalescript,usdutilewidth, usdutileheight, usdumaskblur, usduredraw, usduSeamsfix, usdusdenoise, usduswidth, usduspadding, usdusmaskblur,controlnetenabled, controlnetmodel,controlnetblockymode)
  File "C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\extensions\OneButtonPrompt\call_img2img.py", line 182, in call_img2img
    for i in r['images']:
KeyError: 'images'

**Comment by MrGingerSir222** [comment] 2023-06-03 16:29
update again:
actually, the upscale models just randomly disappear even now from OneButtonPrompt. My fix didn't work. When I change where Stable diffusion looks for those models, it will work for a while until I restart the program, then, the extension no longer can find them.

**Comment by AIrjen** [comment] 2023-06-04 05:50
I'm having a lot of trouble to reproduce this. Please bear with me.

Sorry for asking the obvious, but are you using the latest version of One Button Prompt? A few weeks ago, there was a change in how the models and upscalers are loaded.

The loading is actually done now by accessing the same libraries that WebUI has:
![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/24448041-9444-48ea-b715-25ea750a6c9a)

Meaning that it just uses what WebUI also has.

Have you tried just putting the models in the standard set directories, to see if that helps?

I checked whether Vladmantic has done something different, but it seems to still use the same code that WebUI does for this:

![image](https://github.com/AIrjen/OneButtonPrompt/assets/130234949/a7bdf5a2-d022-4c9c-adca-13c82711bebf)

**Comment by MrGingerSir222** [comment] 2023-06-04 14:50
good call on the extension issue. without any besides OneButtonPrompt installed the issue is gone. I'll see if I can find which one is causing the issue for me, and let you know (just for knowledge sake. not expecting you to fix something like that lol).

**Comment by AIrjen** [comment] 2023-06-06 05:49
Hi, thanks for the clear description! I have a very busy week, so I'll only have time to look this weekend I hope.
I have to install Vlad as well, since I'm only running base automatic1111.

As for this error:

_for i in r['images']:
KeyError: 'images'_

This is actually a result of another error. If we call the API, and the API does not return any images, it breaks here.

If I have time this weekend, I will do these reproduction steps. See if it is something I can do to reproduce and fix, or that it needs to be reported to automatic1111/vlad instead. :)

**Comment by AIrjen** [comment] 2023-06-11 06:14
Hi, I installed Vlad this morning and have been running tests. I can't reproduce your problem, even running long batches with seams fix enabled.

I've put out a mini-update with some stability changes for Ultimate SD Upscale (making sure types are set correctly), maybe get latest version and see if that works?

I do still think it might be a memory issue. The stacktrace does start with:
"C:\Users\Gaming\Desktop\Stable Diffusion\Vlad A111\automatic\venv\lib\site-packages\anyio\streams\memory.py"

It could be something specific to Vladmantic, it could be memory not being released properly during the API calls, it could be a specific sampler of upscaler you are using.

I would suggest trying on Automatic1111 as well, to see if the problem persists there as well.

I'm not sure what I can do to help here (besides the minor update I did).

**Comment by noahwh** [comment] 2023-06-18 13:36
FWIW I saw the error from the first comment when I first tried to use this plugin and it was caused by not using the --api command line option. It'd probably be worthwhile to add some error checking to call_txt2img.py to make sure the API is actually responding.

**Comment by AIrjen** [comment] 2023-06-19 16:50
Hi, it is a good idea to implement something around this. Like an automatic wait and retry if there was no image returned. Will put this on my todo list.

**Comment by AIrjen** [comment] 2023-06-20 07:30
I've added a automatic "wait and retry" into txt2img, img2img and extra calls.
It will now try a total of 3 times, each time waiting each longer for each call (10,20,30 seconds)

If there is still no response, a proper error is raised.

I also made a small fix, there was a "None" upscaler which could cause trouble as well. This has now been removed.

**Comment by AIrjen** [comment] 2023-07-01 13:22
Closing this for now. There is no clear reproduction scenario and stability factors have been implemented.

**Closed by AIrjen** 2023-07-01 13:22 UTC
