### ISSUE TITLE
Overwrite subject 

### ISSUE THREAD

**Issue by WeirdScience06** [AIrjen/OneButtonPrompt#29] opened 2023-05-18 20:13 UTC
While using overwrite subject I was using a lora within the text field, this works fine, however if using the automated mode then it causes the script to error out.

`Traceback (most recent call last):3s/it]
  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)

  File "C:\AI\stable-diffusion-webui\extensions\OneButtonPrompt\main.py", line 127, in generateimages
    txt2img = call_txt2img(randomprompt, size ,hiresfix, 0, filenamecomplete,model ,samplingsteps,cfg, hiressteps, denoisestrength,samplingmethod, upscaler,hiresscale,apiurl,qualitygate,quality,runs,negativeprompt)

  File "C:\AI\stable-diffusion-webui\extensions\OneButtonPrompt\call_txt2img.py", line 148, in call_txt2img
    image.save(outputTXT2IMGFull, pnginfo=pnginfo)

  File "C:\AI\stable-diffusion-webui\venv\lib\site-packages\PIL\Image.py", line 2428, in save
    fp = builtins.open(filename, "w+b")

OSError: [Errno 22] Invalid argument: 'C:\\AI\\stable-diffusion-webui\\extensions\\OneButtonPrompt\\./automated_outputs/txt2img/20230518211142_large__young_woman__<lora_BlissV_>_0.png'`

**Comment by AIrjen** [comment] 2023-05-19 06:12
Thanks you! I can tell by the message you posted where the problem is. 
The dynamic filename wants to add the < and > characters.

I just pushed a hotfix, that removes those characters.

I need to test the results, so I'll keep this open until I confirmed the fix.

**Comment by AIrjen** [comment] 2023-05-19 06:19
OK, confirmed that this works and is now fixed.

During testing I always put the keyword in the override prompt, and the LoRA at the suffix. This is why it didn't show up.

Thanks for including the error report, this helped me to identify the problem.

**Closed by AIrjen** 2023-05-19 06:19 UTC
